PortfolioMvc/Models/ErrorViewModel.cs
namespace PortfolioMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PortfolioMvc/Models/Projeto.cs
namespace PortfolioMvc.Models
{
    public class Projeto
    {
        public int ProjetoId { get; set; }
        public string? Titulo { get; set; }
        public string? Descricao { get; set; }
        public string? ImagemURL { get; set; }
        public string? Link { get; set; }
    }
}

PortfolioMvc/ViewModels/ContatoViewModel.cs
namespace PortfolioMvc.ViewModels;

public class ContatoViewModel
{
    public string? Nome { get; set; }
    public string? Email { get; set; }
    public string? Mensagem { get; set; }
}

PortfolioMvc/ViewModels/PortfolioViewModel.cs
using PortfolioMvc.Models;
namespace PortfolioMvc.ViewModels;

public class PortfolioViewModel
{
    public IEnumerable<Projeto>? Projetos { get; set; }
}

PortfolioMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioMvc.Models;
using System.Diagnostics;

namespace PortfolioMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PortfolioMvc/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioMvc.Services;
using PortfolioMvc.ViewModels;

namespace PortfolioMvc.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly IProjetosService _projetoService;
        private readonly IEmailService _emailService;

        public PortfolioController(IProjetosService projetoService, 
            IEmailService emailService)
        {
            _projetoService = projetoService;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            var projetos = _projetoService.GetProjetos().Take(3).ToList();

            var modelo = new PortfolioViewModel()
            {
                Projetos = projetos
            };
            return View(modelo);
        }
        public IActionResult Projetos()
        {
            var projetos = _projetoService.GetProjetos();
            return View(projetos);
        }

        [HttpGet]
        public IActionResult Contato()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contato(ContatoViewModel contatoViewModel)
        {
            await _emailService.Enviar(contatoViewModel);
            return RedirectToAction("Obrigado");
        }

        public IActionResult Obrigado()
        {
            return View();
        }
    }
}

PortfolioMvc/Views/Home/Index.cshtml
@* <body class="principal"></body> *@
@{
    ViewData["Title"] = "Home Page";
}

<body class="fundo">

    @* <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> *@


    <div style="width:105%">
        <img src="/imagens/LegiaoKMusicPrincipal.png" class=" principal" style="max-width:100%; min-width:30%">

    </div>
    <div class="apoie" style="width:100%">
        @* <iframe src="https://www.vozdascomunidades.com.br/favelas/projeto-social-cria-vakinha-online-para-realizar-evento-geek-na-favela-do-fumace-saiba-como-ajudar/" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> *@
        <br />
        <br />
        <h3> Para que nossa 1ª Edição do LKM seja possível precisamos de apoio para que esse dia seja incrível ! <br />Na favela tem talentos e podemos ser além do que os noticiários de violência carioca. <br /> <br /> Chave Pix: legiaokmusic@gmail.com </h3>
        <br /><a href="https://www.vakinha.com.br/3991076" target="_blank"><button type="button" class="btn btn-lg btn-primary" style="background-color: #FF66C4" id="botao">Doe</button></a>

    </div>
    </br>
    </br>
    </br>

    <div class="container text-center my-3">
        <h2 class="font-weight-light">Bootstrap Multi Slide Carousel</h2>
        <div class="row mx-auto my-auto justify-content-center">
            <div id="recipeCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img">
                                    <img src="/imagens/lampiao.png" class="img-fluid flex">
                                </div> <div class="card-img-overlay"></div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img">
                                    <img src="//via.placeholder.com/500x400/e66?text=2" class="img-fluid flex">
                                </div>
                                <div class="card-img-overlay">Slide 2</div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img">
                                    <img src="//via.placeholder.com/500x400/7d2?text=3" class="img-fluid">
                                </div>
                                <div class="card-img-overlay">Slide 3</div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img"> <img src="//via.placeholder.com/500x400?text=4" class="img-fluid"> </div>
                                <div class="card-img-overlay">Slide 4</div>
                            </div>
                        </div>
                    </div> <div class="carousel-item">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img">
                                    <img src="//via.placeholder.com/500x400/aba?text=5" class="img-fluid">
                                </div>
                                <div class="card-img-overlay">Slide 5</div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="col-md-3">
                            <div class="card">
                                <div class="card-img"> <img src="//via.placeholder.com/500x400/fc0?text=6" class="img-fluid"> </div>
                                <div class="card-img-overlay">Slide 6</div>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            </div>
        </div> <h5 class="mt-2 fw-light">advances one slide at a time</h5>
    </div>


    <button type="button" class="btn btn-primary" onclick="oi()" >Primary</button>

    <script>

        let items = document.querySelectorAll('.carousel .carousel-item')

        items.forEach((el) => {
            const minPerSlide = 6
            let next = el.nextElementSibling
            for (var i = 1; i < minPerSlide; i++) {
                if (!next) {
                    // wrap carousel by using first child
                    next = items[0]
                }
                let cloneChild = next.cloneNode(true)
                el.appendChild(cloneChild.children[0])
                next = next.nextElementSibling
            }
        })
        
       function oi(){

            window.location.href = "/contato";
       }

    </script>











    <div class="container" id="trasnporte" style="max-width:100%; min-width:30%">
        <div class="row">
            <div class="col-6" id="informacoes">
                </br>
                </br>


                <h1 class="informacao">Como Chegar</h1>

                </br>


                <h6> Quem vem de Campo Grande, Santa Cruz e região:</h6>

                <h7>
                    <a target="_blank" href="https://maps.app.goo.gl/pgiqAPpDDsPSnqfM8">Trem Ramal Santa Cruz : Soltar na Estação de Realengo.* Pegar Aplicativo de transporte ou Mototaxi</a><br />


                    <h6> Quem vem de Campo Grande, Santa Cruz e região de Ônibus:</h6>

                    <a target="_blank" href="https://maps.app.goo.gl/eMCrCvpWZ54U6AVV7"> Vans e ônibus que vão para o Metrô de Coelho Neto.<br /></a>
                    <a target="_blank" href="https://maps.app.goo.gl/eMCrCvpWZ54U6AVV7"> 731 - Campo Grande x Marechal Hermes .<br /></a>
                    <a target="_blank" href="https://maps.app.goo.gl/eMCrCvpWZ54U6AVV7"> 397 - Campo Grande x Candelária.<br /> </a>
                    <a target="_blank" href="https://maps.app.goo.gl/eMCrCvpWZ54U6AVV7"> 790  - Campo Grande x Cascadura.<br /></a>
                </h7><br />


                <h6>  Quem vem da Zona Norte ou Centro (Trem Ramal Santa Cruz): </h6>

                <h7>
                    <a target="_blank" href="https://maps.app.goo.gl/YmgyEW4FTtHL5vz77">Soltar na Estação de Magalhães Bastos ( Pegar Moto ou Aplicativo) : Estrada da Água Branca 988 - Realengo.<br /></a><br />

                    <h6>  Quem vem da Zona Norte ou Centro de Ônibus : </h6>

                    <a target="_blank" href="https://maps.app.goo.gl/YmgyEW4FTtHL5vz77">397 - Candelária x Campo Grande .<br /></a>
                    <a target="_blank" href="https://maps.app.goo.gl/YmgyEW4FTtHL5vz77">790 - Cascadura x Campo Grande .<br /></a>
                    <a target="_blank" href="https://maps.app.goo.gl/YmgyEW4FTtHL5vz77">369 - Candelária x Bangu .<br /></a>
                </h7>

            </div>
            <div class="col-6" id="mapa">
                <br />
                <br />
                <h1 class="kpop">Localização</h1>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3676.2480976531924!2d-43.427362624690886!3d-22.86729177928291!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x996113e1425fc5%3A0xa346b647345d4fbc!2sQuadra%20do%20Fumac%C3%AA%20-%20Realengo!5e0!3m2!1spt-BR!2sbr!4v1696260432681!5m2!1spt-BR!2sbr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

            </div>
        </div>
    </div>
</body>

PortfolioMvc/Views/Portfolio/Contato.cshtml
@{
    ViewData["Title"] = "Contato";
}

<img src="~/imagens/contato.jpg" width="100" height="100"/>

<h1>Formulario de Contato</h1>

<form asp-controller="Portfolio" asp-action="Contato">
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" class="form-control" id="nome" name="nome" placeholder="Informe o nome" />
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="nome@email.com" />
    </div>
    <div class="mb-3">
        <label for="mensagem" class="form-label">Mensagem</label>
        <textarea class="form-control" id="mensaje" name="mensagem" rows="4"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

PortfolioMvc/Views/Portfolio/Index.cshtml
@model PortfolioViewModel

@{
    ViewData["Title"] = "Página principal";
}

<partial name="_Apresentacao"/>

<partial name="_Experiencia"/>

<partial name="_ProjetosAmostra" model="Model?.Projetos"/>

<partial name="_Rodape"/>

PortfolioMvc/Views/Portfolio/Obrigado.cshtml
<div class="jumbotron jumbotron-fluid">
  <div class="container">

    <h3 class="display-4">Grato pelo seu contato</h3>
      <p>Vou responder sua mensagem o mais brever possível.</p>  
      <hr class="my-4">
      <p class="lead">
       <div><a asp-action="Index" asp-controller="Home">Retornar</a></div>
     </p>
  </div>
</div>

PortfolioMvc/Views/Portfolio/Projetos.cshtml
@model IEnumerable<Projeto>

@{
    ViewData["Title"] = "Projetos";
}

<div class="container">
    <h1>Meus projetos</h1>
    <p>Principais projetos onde trabalhei</p>
</div>

<partial name="_Projetos" model="Model" />

PortfolioMvc/Views/Shared/_Apresentacao.cshtml
<div class="text-center">
    <h4 class="display-3">Olá, sou o Macoratti</h4>

    <h5>Sou desenvolvedor especializado em tecnologías .NET.</h5>

    <img id="foto"
         src="~/imagens/macoratti.jpg" alt="Foto do Macoratti" />

</div>
<div class="text-center">
    <img id="imagem-dotnet" src="~/imagens/dotnet1.jpg" alt="logo dotnet" />
</div>

<div class="row justify-content-center text-center" style="background-color : #f7f7f7">
    <div class="col col-md-7 secao-bemvindo">
        <h3>Bem-vindo ao meu portfólio</h3>
        <p>
         Estou atuando no mercado há mais de 20 anos onde trabalhei com diversas equipes e em diversos cenários usando as mais variadas tecnologias e oferecendo soluções para desktop, web e mobile.         
        </p>
    </div>
</div>

PortfolioMvc/Views/Shared/_Experiencia.cshtml
<div style="margin-top: -105px">

    <div class="row justify-content-md-center text-center">
        <div class="col col-3 bg-white experiencia" style="border-radius: 15px 0 0 15px; box-shadow: 0 5px 5px 0 gray">
           <i class="bi-hdd-fill"></i>
            <h3>Back-end</h3>

            <p>
                Desenvolvimento de aplicações back-end robustas desde o projeto, testes unitários e deploy em produção 
            </p>

            <p class="text-primary cabecalho">
                Stack:
            </p>

            <p>
                ASP.NET Core, SQL Server
            </p>

            <p class="text-primary cabecalho">
                Experiência:
            </p>

            <ul>
                <li>Web APIs</li>
                <li>ASP.NET Core MVC</li>
                <li>Entity Framework Core</li>
                <li>Blazor</li>
                <li>Dapper</li>
                <li>Principios SOLID</li>
            </ul>

        </div>
        <div class="col col-3 bg-white experiencia" style="border-radius: 0 15px 15px 0; box-shadow: 0 5px 5px 0 gray">
            <i class="bi-code-slash"></i>
            <h3>Front-End</h3>
            <p>
                Criação de aplicações front-ends usando as ferramentas mais atuais do mercado integradas ao back-end 
            </p>

            <p class="text-primary cabecalho">
                Stack:
            </p>

            <p>
                React, Angular, Blazor
            </p>

            <p class="text-primary cabecalho">
                Experiência:
            </p>

            <ul>
                <li>React Hooks</li>
                <li>Angular Material</li>
                <li>Blazor WASM</li>
                <li>jQuery</li>
                <li>Javascript</li>
                <li>HTML/CSS</li>
            </ul>
        </div>
    </div>
</div>

PortfolioMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewData["Title"] - Rolé Favela Geek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PortfolioMvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/portfolio.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" /> *@
</head>
<body>
    <header>

        <div class="container">
            <div class="row">

                <div class="topnav right-content " id="myTopnav">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><h4> Rolé Favela Geek</h4></a>
                    <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Index"><h4>Portfólio</h4></a>
                    <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Projetos"><h4>Projetos</h4></a>
                    <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Contato"><h4>Contato</h4></a>
                    @* <a href="https://www.instagram.com/legiaokmusic/" target="_blank" id="redesocial"><h5 class="bi bi-instagram right-icons "></h5></a> *@
                    @* <a href="https://www.tiktok.com/legiaokmusic?_t=8gApYkPl9pm&_r=1" target="_blank" id="redesocial"> <h5 class=" bi bi-tiktok right-icons "></h5></a> *@
                    @* <a href="https://www.facebook.com/profile.php?id=61550610328195&mibextid=ZbWKwL" target="_blank" id="redesocial"> <h5 class=" bi bi-facebook right-icons "></h5></a> *@
                    @* <a href="https://www.linkedin.com/company/legi%C3%A3o-k-music/" target="_blank" id="redesocial"> <h5 class=" bi bi-linkedin right-icons"></h5></a> *@

                    <a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fa fa-bars"></i></a>
                </div>
              @*   <div class="topnav " id="myTopnav">
                    

                </div> *@
            </div>
        </div>


    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";
            }
        }
    </script>

    @* <footer class="border-top footer text-muted">
    <div class="container" id="textorodape">
    &copy; 2023 - Legião K-Music - @* <a asp-area="" asp-controller="Portfolio" asp-action="Index">Portfolio</a> *@

    @* </div> *@
    @* </footer> *@
    <div id="footer" class=" corfooter text-center">
        <div class="container-fluid">
            <div class="socials-media text-center">
                <ul class="list-unstyled">
                    <li><a href="https://www.instagram.com/legiaokmusic/" target="_blank"><h5 class="kpop bi bi-instagram"></h5></a></li>
                    <li><a href="https://www.tiktok.com/legiaokmusic?_t=8gApYkPl9pm&_r=1" target="_blank"> <h5 class="kpop bi bi-tiktok"></h5></a></li>
                    <li><a href="https://www.facebook.com/profile.php?id=61550610328195&mibextid=ZbWKwL" target="_blank"> <h5 class="kpop bi bi-facebook"></h5></a></li>
                    <li><a href="https://www.linkedin.com/company/legi%C3%A3o-k-music/" target="_blank"> <h5 class="kpop bi bi-linkedin"></h5></a></li>
                </ul>
            </div>
            @*  <div class="row">
            <div class="col-3" id="informacoes">
            <a href="https://www.instagram.com/legiaokmusic/" target="_blank"><h5 class="kpop bi bi-instagram">Instagram</h5></a>
            </div>
            <div class="col-3">
            <a href="https://www.tiktok.com/legiaokmusic?_t=8gApYkPl9pm&_r=1" target="_blank"> <h5 class="kpop bi bi-tiktok">TikTok</h5></a>
            </div>
            <div class="col-3">
            <a href="https://www.facebook.com/profile.php?id=61550610328195&mibextid=ZbWKwL" target="_blank"> <h5 class="kpop bi bi-facebook">Facebook</h5></a>
            </div>
            <div class="col-3">
            <a href="https://www.linkedin.com/company/legi%C3%A3o-k-music/" target="_blank"> <h5 class="kpop bi bi-linkedin">Linkedin</h5></a>
            </div>
            </div> *@
            <p>&copy; Copyright André Guterres</p>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PortfolioMvc/Views/Shared/_Projetos.cshtml
@model IEnumerable<Projeto>

@if (Model is not null)
{
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var projeto in Model)
            {
                <div class="col">
                    <div class="card h-100">
                        <img src="@projeto.ImagemURL" class="card-img-top" alt="imagem projeto" />
                        <div class="card-body">
                            <h5 class="card-title">@projeto.Titulo</h5>
                            <p class="card-text">@projeto.Descricao</p>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary" href="@projeto.Link" target="_blank"
                            rel="noopener noreferrer">Visitar</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}

PortfolioMvc/Views/Shared/_ProjetosAmostra.cshtml
@model IEnumerable<Projeto>

@if (Model is not null)
{
    <div class="text-center" style="padding-top: 6rem;">
        <h1>Projetos mais recentes</h1>
        <p>Alguns dos projetos mais recentes onde trabalhei.</p>
    </div>

    <partial name="_Projetos" model="Model" />
}

PortfolioMvc/Views/Shared/_Rodape.cshtml
<div id="footer" class="text-center">
    <div class="container-fluid">
        <div class="socials-media text-center">
            <ul class="list-unstyled">
                <li><a href="https://www.facebook.com/Macoratti.net/"><i class="bi bi-facebook"></i></a></li>
                <li><a href="https://twitter.com/macorati"><i class="bi bi-twitter"></i></a></li>
                <li><a href="https://www.instagram.com/macorattinet/"><i class="bi bi-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/in/jose-macoratti-2507156a/"><i class="bi bi-linkedin"></i></a></li>
            </ul>
        </div>
        <p>&copy; Copyright Macoratti.net</p>
    </div>
</div>